# dosconio/COTLAB, powered by unisym
#{TEMP} only for 64-bit
BINDIR := /usr/bin

all: # build sources for `install`
	-mv libl64 libl64.a
	g++ -D_DEBUG -D_Linux src/*.cpp -Iinc -L. -ll64 -O3 -o cot -Wno-unused-result
install: # a must
	mkdir -p ${DESTDIR}${BINDIR}
	cp ./cot ${DESTDIR}${BINDIR}/
	
